http:
  middlewares:
    block-ips:
      ipWhiteList:
        sourceRange:
          - "192.168.1.0/24"
          - "10.0.0.0/8"
          - "1.2.3.4/32"
          # Add your large list of IPs and CIDRs here
        block: true # Block listed IPs instead of whitelisting
